
    create table project2.choiceselections (
        attempt_id integer not null,
        choice_id integer not null,
        primary key (attempt_id, choice_id)
    );

    create table project2.courses (
        course_id integer generated by default as identity,
        educator_id integer,
        price NUMERIC(10, 2),
        creation_date timestamp(6),
        category varchar(255),
        description varchar(255),
        img_url varchar(255),
        title varchar(255),
        primary key (course_id)
    );

    create table project2.educator (
        educator_id integer generated by default as identity,
        alma_mater varchar(255),
        degree_level varchar(255),
        degree_major varchar(255),
        year_of_hire varchar(255),
        primary key (educator_id)
    );

    create table project2.enrollments (
        course_id integer,
        course_rating integer,
        enrollment_id integer generated by default as identity,
        enrollment_status boolean,
        student_id integer,
        enrollment_date timestamp(6),
        course_review varchar(255),
        payment_status varchar(255) check (payment_status in ('pending','completed','cancelled')),
        primary key (enrollment_id)
    );

    create table project2.questionchoices (
        choice_id integer generated by default as identity,
        correct boolean,
        question_id integer,
        text varchar(255),
        primary key (choice_id)
    );

    create table project2.quizattempts (
        attempt_id integer generated by default as identity,
        quiz_id int not null,
        score numeric(4,2) check (score <= 100) not null,
        student_id integer not null,
        attempt_date timestamp not null,
        primary key (attempt_id)
    );

    create table project2.quizquestions (
        question_id integer generated by default as identity,
        quiz_id integer not null,
        question_text varchar(255) not null,
        primary key (question_id)
    );

    create table project2.quizzes (
        attempts_allowed integer not null,
        course_id integer,
        open boolean not null,
        quiz_id integer generated by default as identity,
        timer integer not null,
        title varchar(255),
        primary key (quiz_id)
    );

    create table project2.users (
        user_id integer generated by default as identity,
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('student','educator')),
        primary key (user_id)
    );

    alter table if exists project2.quizattempts 
       add constraint FKfhhkmlk6b2sstt3e2gy3drwny 
       foreign key (quiz_id) 
       references project2.quizzes;

    alter table if exists project2.quizattempts 
       add constraint FKrysyev381nhi9uhtaoxjfo46j 
       foreign key (student_id) 
       references project2.users;
